sudo: required

env:
  global:
    - CC_TEST_REPORTER_ID=a58ddd1aae49507de14f527e7dfee18af02fb39ca1dffb350102ba123e3e1e0a

language: generic

services:
  - docker

install:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build --force-recreate -d
  - docker ps -a
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - docker-compose exec web bundle exec rake

after_script:
  - docker cp releases_web_1:/usr/src/app/coverage/.resultset.json ./.resultset.json
  - ls -la
  - ./cc-test-reporter format-coverage ./.resultset.json --prefix /usr/src/app -t simplecov -o ./codeclimate.backend.json
  - ./cc-test-reporter sum-coverage ./codeclimate.*.json -p 1 -o ./codeclimate.total.json
  - ./cc-test-reporter upload-coverage -i ./codeclimate.total.json